### ISSUE TITLE
Serialization Context Dynamically during POST request

### ISSUE THREAD

**Issue by a-dasilva** [api-platform/docs#410]
Hello everyone, I have the same issue as related on https://github.com/api-platform/docs/issues/298.

In the documentation, this is not really precise on this point, especially during denormalization.
https://api-platform.com/docs/core/serialization#changing-the-serialization-context-dynamically

```
public function createFromRequest(Request $request, bool $normalization, array $extractedAttributes = null) : array
{
    $context = $this->decorated->createFromRequest($request, $normalization, $extractedAttributes);
    $subject = $request->attributes->get('data');

    if ($subject instanceof Book && isset($context['groups']) && $this->authorizationChecker->isGranted('ROLE_ADMIN') && false === $normalization) {
        $context['groups'][] = 'admin_input';
    }

    return $context;
}
```

Here, `$subject` is null in denormalization, is this a normal behaviour ?

Thank you in advance, I love this project ❤️

**Comment by antograssiot** [comment]
I think that it is expected. As you can see in [here in the ReadLister](https://github.com/api-platform/core/blob/master/src/EventListener/ReadListener.php#L71-L86) the contextBuilder is called before retriving data from the Dataprovider and thus deserializing the object, it is king of logical that you can't access the object until you know how to deserialize it.

I think that is should be `$context['resource_class'] === Book::class` instead of `$subject instanceof Book`

**Comment by a-dasilva** [comment]
Thank you @antograssiot, I agree and I think that solve the problem. Have a nice day
